Add employee subjects
DamboySytesNet/mobile pull request #37
Opened 2019-12-12 23:22 UTC by Karbowskii

2019-12-13 00:21 UTC, Karbowskii commented
Wydaje mi się że jest skończone, błędy które znalazłem już naprawiłem :>
Czekam na review

2019-12-19 12:42 UTC, ZielaA requested changes

2019-12-19 12:42 UTC, ZielaA commented on app/activities/employee/cockpit/cockpit.js
> +        frameModule.topmost() .navigate(
Deprecated

2019-12-19 12:42 UTC, ZielaA commented on app/activities/employee/cockpit/cockpit.js
> +        frameModule.topmost() .navigate(
Deprecated

2019-12-19 12:42 UTC, ZielaA commented on app/activities/employee/subjects/subjects.js
> +    let page = args.object;
Chyba jednak przyjęliśmy taktykę, że page jest zmienną globalną. Można ją wywalić na zewnątrz, żeby za każdym razem jej nie wczytywać.

2019-12-19 12:42 UTC, ZielaA commented on app/activities/employee/subjects/subjects.js
> +}]
Może wywal te testowe dane do osobnego pliku

2019-12-19 12:42 UTC, ZielaA commented on app/activities/employee/subjects/subjects.js
> +        tmp = pageData.userSubjects.find(el => el.id === id);
to się chyba powinno robić metodą set(name, value)

2019-12-19 12:42 UTC, ZielaA commented on app/activities/employee/subjects/subjects.js
> +    let id = parseInt(args.object.index, 10);
parsowanie nie jest potrzebne

2019-12-19 12:42 UTC, ZielaA commented on app/activities/employee/subjects/subjects.js
> +    let id = parseInt(args.object.index, 10);
parsowanie nie jest potrzebne

2020-01-19 03:54 UTC, Karbowskii commented
następne czym się zajmę to wygląd u studenta ;)

2020-01-20 14:17 UTC, DamboySytesNet approved these changes

2020-01-20 14:18 UTC, DamboySytesNet approved these changes

2020-01-20 14:19 UTC, ZielaA approved these changes

2020-01-20 14:20 UTC, merged